Vagrant.configure("2") do |config|
  config.vm.box = "rockylinux/9"
  config.vm.box_version = "6.0.0"

  nodes = {
    "lb" => "192.168.100.10",
    "cp1" => "192.168.100.11",
    "w1"  => "192.168.100.12",
    "w2"  => "192.168.100.13"
  }

  # config.vm.define "lb" do |node|
  #   node.vm.network :private_network, ip: "192.168.56.100", hostname: true
  #   node.vm.network "forwarded_port", guest: 6443, host: 6443
  #   node.vm.hostname = "lb.local"
  #   node.vm.provider "virtualbox" do |vb|
  #     vb.name = "k8s-the-hard-way-lb"
  #     vb.memory = "1024"
  #     vb.cpus = 1
  #     vb.linked_clone = true
  #   end

  #   node.vm.synced_folder "share/dl", "/downloads", create: true

  #   node.vm.provision "shell", inline: common_script
  #   node.vm.provision "ansible" do |ansible|
  #     ansible.verbose = "vv"
  #     ansible.playbook = "bootstrap.yml"
  #     ansible.compatibility_mode = "2.0"
  #   end
  # end

  nodes.each do |name, ip|
    config.vm.define name do |node|
      node.vm.hostname = name

      node.vm.network "private_network", ip: ip, hostname: true
      node.vm.hostname = "#{name}"
      if name == "lb" or name == "cp1"
        node.vm.network "forwarded_port", guest: 6443, host: 6443
      end
      node.vm.synced_folder "shared/dl", "/downloads", create: true

      node.vm.provider :libvirt do |lv|
        lv.memory = name == "cp1" ? 2048 : 1024
        lv.cpus   = name == "cp1" ? 2 : 2
      end
      node.vm.provision "shell", inline: <<-SHELL
        sed -i 's/^#{ip}.*/#{ip}\t#{name}.kubernetes.local\t#{name}/' /etc/hosts
        grep -Pq "192.168.100.10\tlb.kubernetes.local\tlb"  /etc/hosts  || echo -e "192.168.100.10\tlb.kubernetes.local\tlb" >> /etc/hosts
        grep -Pq "192.168.100.11\tcp1.kubernetes.local\tcp1" /etc/hosts || echo -e "192.168.100.11\tcp1.kubernetes.local\tcp1" >> /etc/hosts
        grep -Pq "192.168.100.12\tw1.kubernetes.local\tw1" /etc/hosts || echo -e "192.168.100.12\tw1.kubernetes.local\tw1" >> /etc/hosts
        grep -Pq "192.168.100.13\tw2.kubernetes.local\tw2" /etc/hosts || echo -e "192.168.100.13\tw2.kubernetes.local\tw2" >> /etc/hosts
        # Root passwordless login
        mkdir -p ~/.ssh
        cat /downloads/root.pub >> ~/.ssh/authorized_keys
        chmod 600 ~/.ssh/authorized_keys
        sed -i 's/^#*PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config
        systemctl restart sshd
        # User access
        cat "/downloads/id_rsa.pub" >> /home/vagrant/.ssh/authorized_keys
        chmod 600 /home/vagrant/.ssh/authorized_keys
        chown vagrant:vagrant /home/vagrant/.ssh/authorized_keys
        cp /downloads/id_rsa /home/vagrant/.ssh/id_rsa
        chmod 600 /home/vagrant/.ssh/id_rsa
        chown vagrant:vagrant /home/vagrant/.ssh/id_rsa
      SHELL
    end
  end
end
