Vagrant.configure("2") do |config|
  config.vm.box = "rockylinux/9"
  config.vm.box_version = "6.0.0"

  nodes = {
    "cp1" => "192.168.100.11",
    "w1"  => "192.168.100.12",
    "w2"  => "192.168.100.13"
  }

  nodes.each do |name, ip|
    config.vm.define name do |node|
      node.vm.hostname = name

      node.vm.network "private_network", ip: ip, hostname: true
      node.vm.hostname = "#{name}"
      if name == "cp1"
        node.vm.network "forwarded_port", guest: 6443, host: 6443
      end
      node.vm.synced_folder "shared/dl", "/downloads", create: true

      node.vm.provider :libvirt do |lv|
        lv.memory = name == "cp1" ? 2048 : 1024
        lv.cpus   = name == "cp1" ? 2 : 2
      end

      node.vm.provision "shell", inline: <<-SHELL
        sed -i 's/^#{ip}.*/#{ip}\t#{name}.kubernetes.local\t#{name}/' /etc/hosts
        grep -Pq "192.168.100.11\tcp1.kubernetes.local\tcp1" /etc/hosts || echo -e "192.168.100.11\tcp1.kubernetes.local\tcp1" >> /etc/hosts
        grep -Pq "192.168.100.12\tw1.kubernetes.local\tw1" /etc/hosts || echo -e "192.168.100.12\tw1.kubernetes.local\tw1" >> /etc/hosts
        grep -Pq "192.168.100.13\tw2.kubernetes.local\tw2" /etc/hosts || echo -e "192.168.100.13\tw2.kubernetes.local\tw2" >> /etc/hosts
        # Root passwordless login
        mkdir -p ~/.ssh
        cat /downloads/root.pub >> ~/.ssh/authorized_keys
        chmod 600 ~/.ssh/authorized_keys
        sed -i 's/^#*PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config
        systemctl restart sshd
        # User access
        cat "/downloads/id_rsa.pub" >> /home/vagrant/.ssh/authorized_keys
        chmod 600 /home/vagrant/.ssh/authorized_keys
        chown vagrant:vagrant /home/vagrant/.ssh/authorized_keys
        cp /downloads/id_rsa /home/vagrant/.ssh/id_rsa
        chmod 600 /home/vagrant/.ssh/id_rsa
        chown vagrant:vagrant /home/vagrant/.ssh/id_rsa
      SHELL
    end
  end
end
